version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ~/Documents/home-assistant/:/config
      - /etc/localtime:/etc/localtime:ro
      - /media/frigate:/frigate-drive
      - /media/backup:/backup_drive
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
