# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages
  customize:
    input_boolean.trash_has_been_taken_out:
      device_class: battery_charging


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

recorder:
  purge_keep_days: 400
  auto_purge: true
  db_url: !secret db_url
  exclude:
    entity_globs:
      - automation.*stopwatch
      - input_boolean.*stopwatch
      - sensor.*stopwatch
      - select.baby_buddy*
      - input_boolean.waiting_for*
      - input_button.confirm_*
      - input_text.finnley_*
      - input_number.finnley_*
      - input_datetime.finnley_*
      - input_datetime.pumping_time
      - input_datetime.baby_buddy*
      - media_player.*
      - timer.finnley*
      - tts.*
      - update.*
      - weather.*
      - vaccuum.*
      - button.*ping
      - sensor.bb_*
      - sensor.sun*
      - weather.*

# Spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

# ourgroceries:
#   username: !secret our_groceries_username
#   password: !secret our_groceries_password


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
rest_command: !include rest_commands.yaml

binary_sensor: !include binary_sensors.yaml

sensor: !include sensors.yaml

input_select: !include input_selects.yaml

input_text: !include input_texts.yaml

notify:
  - platform: group
    name: "branden_desktop_group"
    services:
      - service: branden_desktop
  - platform: group
    name: "All Mobile Phones"
    services:
      - service: mobile_app_samantha_s_phone
      - service: mobile_app_branden_s_phone

panel_iframe:
  baby_buddy:
    title: "Baby Buddy 2"
    url: !secret baby_buddy_auth_url

#test comment8
