- platform: systemmonitor
  scan_interval: 240
  resources:
    - type: disk_use
      arg: /config
    - type: disk_free
      arg: /config
    - type: disk_use
      arg: /frigate-drive
    - type: disk_free
      arg: /frigate-drive
    - type: disk_use
      arg: /backup_drive
    - type: disk_free
      arg: /backup_drive
    - type: memory_use
    - type: memory_free
    - type: last_boot
    - type: processor_use
    - type: processor_temperature
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
- platform: rest
  resource: https://api.weather.gov/alerts/active/count
  name: NWS Alert Count
  value_template: >
    {% if value_json.zones.KSZ105 is defined %}
      {{ value_json.zones.KSZ105 }}
    {% else %}
      0
    {% endif %}
  headers:
    User-Agent: Homeassistant
    Accept: application/ld+json
  scan_interval: 60
    
- platform: rest
  resource: https://api.weather.gov/alerts/active?zone=KSZ105
  name: NWS Alert Event
  value_template: >
    {% if value_json.features is defined %}
      {{ value_json['features']|map(attribute="properties")|map(attribute="event")|join(' | ') }}
    {% else %}
      None
    {% endif %}
  json_attributes:
    - features
  headers:
    User-Agent: Homeassistant
    Accept: application/geo+json
  scan_interval: 60

      ##########################################################
      ## BabyBuddy Feedings
      ##########################################################

- platform: rest
  scan_interval: 15
  name: BabyBuddy Feedings
  resource: http://192.168.86.21:8000/api/feedings/?limit=20
  value_template: N/A
  json_attributes:
    - results
  headers:
    Authorization: !secret baby_buddy_token

- platform: rest
  scan_interval: 15
  name: BabyBuddy Pumpings
  resource: http://192.168.86.21:8000/api/pumping/?limit=2
  value_template: N/A
  json_attributes:
    - results
  headers:
    Authorization: !secret baby_buddy_token

- platform: template
  sensors:
    bb_last_pumping:
      friendly_name: Last Pumping
      value_template: >-
        {{state_attr('sensor.babybuddy_pumpings', 'results')[0]["amount"]}}oz @ {{ as_timestamp(state_attr('sensor.babybuddy_pumpings', 'results')[0]["start"]) | timestamp_custom ("%-I:%M %p", True) }}

    bb_last_pumping_notes:
      friendly_name: Last Pumping Notes
      value_template: >-
        {{state_attr('sensor.babybuddy_pumpings', 'results')[0]["notes"] or ''}}

    bb_last_feeding_time:
      friendly_name: Last Feeding Time
      value_template: >-
        {{ as_timestamp(state_attr('sensor.babybuddy_feedings', 'results')[0]["start"]) | timestamp_custom ("%-I:%M %p", True) }}

    bb_last_breast_feeding_notes:
      friendly_name: Last Breast Feeding Notes
      value_template: >-
        {% set last_breast_milk_feeding = state_attr('sensor.babybuddy_feedings', 'results') | selectattr('child', 'equalto', 1) | selectattr('method', 'in', ['left breast', 'right breast', 'both breasts']) | list | first %}
        {{last_breast_milk_feeding.notes or ''}}

    bb_last_bottle_feeding_notes:
      friendly_name: Last Bottle Feeding Notes
      value_template: >-
        {% set last_bottle_feeding = state_attr('sensor.babybuddy_feedings', 'results') | selectattr('child', 'equalto', 1) | selectattr('method', 'equalto', 'bottle') | list | first%}
        {{last_bottle_feeding.notes or ''}}
    
    bb_last_bottle_amount:
      friendly_name: Last Bottle Amount
      value_template: >-
        {% set last_bottle_feeding = state_attr('sensor.babybuddy_feedings', 'results') | selectattr('child', 'equalto', 1) | selectattr('method', 'equalto', 'bottle') | list | first%}
        {{last_bottle_feeding.amount}}oz of {{last_bottle_feeding.type.title()}} @ {{as_timestamp(last_bottle_feeding.start) | timestamp_custom ("%-I:%M %p", True)}} 

    bb_last_breast_feeding:
      friendly_name: Last Breast Feeding
      value_template: >-
        {% set last_breast_milk_feeding = state_attr('sensor.babybuddy_feedings', 'results') | selectattr('child', 'equalto', 1) | selectattr('method', 'in', ['left breast', 'right breast', 'both breasts']) | list | first %}
        {{((as_timestamp(last_breast_milk_feeding.end) - as_timestamp(last_breast_milk_feeding.start))/60) | round(2)}} min(s) on {{last_breast_milk_feeding.method.title()}} @ {{as_timestamp(last_breast_milk_feeding.start) | timestamp_custom ("%-I:%M %p", True)}}


    bb_last_feeding_how_long_ago:
      friendly_name: Last Feeding How Long Ago
      value_template: >-
        {% set up_time = as_timestamp(now()) - as_timestamp(state_attr('sensor.babybuddy_feedings', 'results')[0]["start"]) %}
        {% set seconds = (up_time % 60) | int %}
        {% set minutes = (up_time // 60) | int %}
        {% set hours = (minutes // 60) %}
        {% set days = (hours // 24) %}
        {% set weeks = (days // 7) %}
        {% set minutes = (minutes % 60) %}
        {% set hours =  (hours % 24) %}
        {% set days = (days % 7) %}
        {% macro phrase(value, name) %}
                  {%- set value = value %}
                  {%- set end = 's' if value > 1 else '' %}
                  {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }}
        {%- endmacro %}
        {% macro phraseSeconds(value) %}
                  {%- set value = value %}
                  {%- set end = 's' if value > 0 else '' %}
                  {{- '{}{}'.format(value, end) if value | int > 0 else '' }}
        {%- endmacro %}
        {% set text = [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min') ] | select('!=','') | list | join(', ') %}
        {% set last_comma = text.rfind(',') %}
        {% if last_comma != -1 %}
          {% set text = text[:last_comma] + ' and' + text[last_comma + 1:] %}
        {% endif %}
        {{ text }} ago